//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RinkuEntities : DbContext
    {
        public DB_RinkuEntities()
            : base("name=DB_RinkuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<CatalogoTipoEmpleado> CatalogoTipoEmpleado { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<CatalogoRol> CatalogoRol { get; set; }
        public virtual DbSet<CatalogoImpuesto> CatalogoImpuesto { get; set; }
    }
}
