//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoImpuesto
    {
        public byte Codigo { get; set; }
        public byte ISRNormal { get; set; }
        public byte ISRExtra { get; set; }
        public int TopeSalario { get; set; }
    }
}
